# Data Aggregation

In [2]:
import pandas as pd
import numpy as np
import hvplot.pandas
from pathlib import Path

## Numerical Aggregation

In [3]:
# Create a DataFrame for prices and zip codes.
houses_df = pd.DataFrame({
    'prices (in thousands))': np.random.randint(100, 1000, 100),
    'zip': np.random.choice([90210, 60606], 100)
})
display(houses_df.head())
display(houses_df.tail())

   prices (in thousands))    zip
0                     216  60606
1                     424  90210
2                     525  90210
3                     118  90210
4                     583  90210

    prices (in thousands))    zip
95                     600  90210
96                     810  90210
97                     225  90210
98                     272  90210
99                     652  90210

In [4]:
# Filter out only zip codes that equal 90210.
prices_90210 = houses_df.loc[houses_df['zip'] == 90210]
prices_90210.mean()

prices (in thousands))      579.018182
zip                       90210.000000
dtype: float64

In [5]:
# Run the groupby function on 'zip' without aggregation
houses_df.groupby('zip')

In [6]:
#Run the groupby function in 'zip' with aggregation
houses_df.groupby('zip').mean()

       prices (in thousands))
zip
60606              469.955556
90210              579.018182

## Visual Aggregation

In [7]:
# Create the DataFrame to compare AK and CA.
ak_data = np.arange(100)
bias = np.random.uniform(0, 10, 100)
ca_data = 2*ak_data + bias
df = pd.DataFrame({
    "AK": ak_data,
    "CA": ca_data
})

In [8]:
# Create a scatter plot to show the relationship between AK and CA.
df.hvplot.scatter(x="AK", y="CA")

:Scatter   [AK]   (CA)

In [ ]:
! pip install jupyter_bokeh -q

Requirement already satisfied: jupyter_bokeh in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (4.0.5)
Requirement already satisfied: bokeh==3.* in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from jupyter_bokeh) (3.7.3)
Requirement already satisfied: ipywidgets==8.* in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from jupyter_bokeh) (8.1.7)
Requirement already satisfied: Jinja2>=2.9 in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from bokeh==3.*->jupyter_bokeh) (3.1.6)
Requirement already satisfied: contourpy>=1.2 in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from bokeh==3.*->jupyter_bokeh) (1.3.3)
Requirement already satisfied: narwhals>=1.13 in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from bokeh==3.*->jupyter_bokeh) (2.1.1)
Requirement already satisfied: numpy>=1.16 in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from bokeh==3.*->jupyter_bokeh) (2.2.6)
Requirement already satisfied: packaging>=16.8 in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from bokeh==3.*->jupyter_bokeh) (25.0)
Requirement already satisfied: pandas>=1.2 in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from bokeh==3.*->jupyter_bokeh) (2.3.1)
Requirement already satisfied: pillow>=7.1.0 in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from bokeh==3.*->jupyter_bokeh) (11.3.0)
Requirement already satisfied: PyYAML>=3.10 in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from bokeh==3.*->jupyter_bokeh) (6.0.2)
Requirement already satisfied: tornado>=6.2 in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from bokeh==3.*->jupyter_bokeh) (6.5.2)
Requirement already satisfied: xyzservices>=2021.09.1 in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from bokeh==3.*->jupyter_bokeh) (2025.4.0)
Requirement already satisfied: comm>=0.1.3 in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from ipywidgets==8.*->jupyter_bokeh) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from ipywidgets==8.*->jupyter_bokeh) (9.4.0)
Requirement already satisfied: traitlets>=4.3.1 in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from ipywidgets==8.*->jupyter_bokeh) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from ipywidgets==8.*->jupyter_bokeh) (4.0.14)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from ipywidgets==8.*->jupyter_bokeh) (3.0.15)
Requirement already satisfied: decorator in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (1.1.1)
Requirement already satisfied: jedi>=0.16 in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (0.19.2)
Requirement already satisfied: matplotlib-inline in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (0.1.7)
Requirement already satisfied: pexpect>4.3 in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (3.0.51)
Requirement already satisfied: pygments>=2.4.0 in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (2.19.2)
Requirement already satisfied: stack_data in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (0.6.3)
Requirement already satisfied: MarkupSafe>=2.0 in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from Jinja2>=2.9->bokeh==3.*->jupyter_bokeh) (3.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from pandas>=1.2->bokeh==3.*->jupyter_bokeh) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from pandas>=1.2->bokeh==3.*->jupyter_bokeh) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from pandas>=1.2->bokeh==3.*->jupyter_bokeh) (2025.2)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (0.8.4)
Requirement already satisfied: ptyprocess>=0.5 in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (0.7.0)
Requirement already satisfied: wcwidth in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (0.2.13)
Requirement already satisfied: six>=1.5 in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=1.2->bokeh==3.*->jupyter_bokeh) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from stack_data->ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (2.2.0)
Requirement already satisfied: asttokens>=2.1.0 in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from stack_data->ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (3.0.0)
Requirement already satisfied: pure-eval in /workspaces/TechCatalyst_DE_2025_3/dev1/lib/python3.12/site-packages (from stack_data->ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (0.2.3)

[notice] A new release of pip is available: 23.2.1 -> 25.2
[notice] To update, run: pip install --upgrade pip

In [10]:
# Create a plot using the groupby parameter.
houses_df.hvplot(groupby="zip")

BokehModel(combine_events=True, render_bundle={'docs_json': {'9d4814c2-9ef1-48be-b344-c58feeae6a78': {'version…